# Generated by Django 5.1.7 on 2025-12-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_liveclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher_reg'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher_reg'),
        ),
        migrations.AlterField(
            model_name='recordedclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher_reg'),
        ),
    ]
