# Generated by Django 5.1.7 on 2025-12-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_homework_teacher_alter_notes_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_reg',
            name='id_card',
            field=models.FileField(default='null', upload_to='proof'),
        ),
    ]
