# Generated by Django 5.1.7 on 2025-12-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0001_initial'),
        ('Teacher', '0004_teacher_reg_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteAdmin.subject'),
        ),
    ]
