# Generated by Django 5.1.7 on 2025-12-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_alter_marks_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
    ]
