# Generated by Django 5.1.7 on 2025-12-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_alter_marks_marks_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='notes',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='recordedclass',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
