# Generated by Django 5.1.7 on 2025-12-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_homework_class_level_liveclass_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
