# Generated by Django 5.1.7 on 2025-12-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_attendance_class_level_marks_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='class_level',
        ),
    ]
