# Generated by Django 5.1.7 on 2025-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0013_attendance_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='class_level',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
