# Generated by Django 5.1.7 on 2026-01-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_marks_class_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
