# Generated by Django 5.1.7 on 2026-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0015_delete_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_reg',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
    ]
