# Generated by Django 5.1.7 on 2026-02-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0016_teacher_reg_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_reg',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
