# Generated by Django 5.1.7 on 2026-01-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
