# Generated by Django 5.1.7 on 2026-01-15 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_initial'),
        ('Student', '0004_studentteachermessage_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewremark',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewremark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_reg'),
        ),
    ]
