# Generated by Django 5.1.7 on 2026-01-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
