# Generated by Django 5.1.7 on 2026-01-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0001_initial'),
        ('SiteAdmin', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(default='null', max_length=20)),
                ('marks_obtained', models.FloatField(default=0)),
                ('total_marks', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parent.parent_reg')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_reg')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteAdmin.subject')),
            ],
        ),
    ]
