# Generated by Django 5.1.7 on 2026-01-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_mark_marks'),
        ('SiteAdmin', '0001_initial'),
        ('Student', '0001_initial'),
        ('Teacher', '0015_delete_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_marks',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_marks', to='Teacher.teacher_reg'),
        ),
        migrations.AlterField(
            model_name='mark_marks',
            name='class_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mark_marks',
            name='marks_obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mark_marks',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_marks', to='Parent.parent_reg'),
        ),
        migrations.AlterField(
            model_name='mark_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='Student.student_reg'),
        ),
        migrations.AlterField(
            model_name='mark_marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='SiteAdmin.subject'),
        ),
    ]
