# Generated by Django 5.1.7 on 2026-01-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0004_parentteachermessage'),
        ('SiteAdmin', '0003_alter_fee_status'),
        ('Student', '0004_studentteachermessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('card_number', models.CharField(max_length=16)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteAdmin.fee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parent.parent_reg')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_reg')),
            ],
        ),
    ]
