# Generated by Django 5.1.7 on 2026-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0002_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
