# Generated by Django 5.1.7 on 2026-01-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0003_alter_fee_status'),
        ('Teacher', '0015_delete_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(default='pending', max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='Teacher.teacher_reg')),
            ],
            options={
                'unique_together': {('teacher', 'month')},
            },
        ),
    ]
