# Generated by Django 5.1.7 on 2026-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0004_teachersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersalary',
            name='paid_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
