# Generated by Django 5.1.7 on 2026-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0005_alter_teachersalary_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersalary',
            name='paid_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
