# Generated by Django 5.1.7 on 2026-01-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0006_alter_teachersalary_paid_date'),
        ('Teacher', '0015_delete_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='notmarked', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='Teacher.teacher_reg')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
