# Generated by Django 5.1.7 on 2026-02-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0007_teacherattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='class_level',
        ),
        migrations.AddField(
            model_name='fee',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_fees', to='SiteAdmin.subject'),
        ),
    ]
