# Generated by Django 5.1.7 on 2026-01-06 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studentteachermessage'),
        ('Teacher', '0015_delete_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteachermessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='studentteachermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentteachermessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_reg'),
        ),
        migrations.AlterField(
            model_name='studentteachermessage',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher_reg'),
        ),
    ]
