# Generated by Django 5.1.7 on 2026-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_studentteachermessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteachermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
